/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyUpdatesRouteImport } from './routes/my-updates'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AccessRequestRouteImport } from './routes/access-request'
import { Route as SignInRouteRouteImport } from './routes/sign-in/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminMembersRouteImport } from './routes/admin/members'
import { Route as AdminCategoryRouteImport } from './routes/admin/category'
import { Route as AdminWeekUpdatesRouteRouteImport } from './routes/admin/week-updates/route'
import { Route as AdminWeekUpdatesIndexRouteImport } from './routes/admin/week-updates/index'
import { Route as AdminWeekUpdatesProjectIdRouteImport } from './routes/admin/week-updates/$projectId'

const MyUpdatesRoute = MyUpdatesRouteImport.update({
  id: '/my-updates',
  path: '/my-updates',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRequestRoute = AccessRequestRouteImport.update({
  id: '/access-request',
  path: '/access-request',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRouteRoute = SignInRouteRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignInRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoryRoute = AdminCategoryRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWeekUpdatesRouteRoute = AdminWeekUpdatesRouteRouteImport.update({
  id: '/week-updates',
  path: '/week-updates',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminWeekUpdatesIndexRoute = AdminWeekUpdatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWeekUpdatesRouteRoute,
} as any)
const AdminWeekUpdatesProjectIdRoute =
  AdminWeekUpdatesProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => AdminWeekUpdatesRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/sign-in': typeof SignInRouteRouteWithChildren
  '/access-request': typeof AccessRequestRoute
  '/home': typeof HomeRoute
  '/my-updates': typeof MyUpdatesRoute
  '/admin/week-updates': typeof AdminWeekUpdatesRouteRouteWithChildren
  '/admin/category': typeof AdminCategoryRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/': typeof AdminIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/admin/week-updates/$projectId': typeof AdminWeekUpdatesProjectIdRoute
  '/admin/week-updates/': typeof AdminWeekUpdatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-request': typeof AccessRequestRoute
  '/home': typeof HomeRoute
  '/my-updates': typeof MyUpdatesRoute
  '/admin/category': typeof AdminCategoryRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin': typeof AdminIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/admin/week-updates/$projectId': typeof AdminWeekUpdatesProjectIdRoute
  '/admin/week-updates': typeof AdminWeekUpdatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/sign-in': typeof SignInRouteRouteWithChildren
  '/access-request': typeof AccessRequestRoute
  '/home': typeof HomeRoute
  '/my-updates': typeof MyUpdatesRoute
  '/admin/week-updates': typeof AdminWeekUpdatesRouteRouteWithChildren
  '/admin/category': typeof AdminCategoryRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/': typeof AdminIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/admin/week-updates/$projectId': typeof AdminWeekUpdatesProjectIdRoute
  '/admin/week-updates/': typeof AdminWeekUpdatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sign-in'
    | '/access-request'
    | '/home'
    | '/my-updates'
    | '/admin/week-updates'
    | '/admin/category'
    | '/admin/members'
    | '/admin/projects'
    | '/admin/'
    | '/sign-in/'
    | '/admin/week-updates/$projectId'
    | '/admin/week-updates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-request'
    | '/home'
    | '/my-updates'
    | '/admin/category'
    | '/admin/members'
    | '/admin/projects'
    | '/admin'
    | '/sign-in'
    | '/admin/week-updates/$projectId'
    | '/admin/week-updates'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sign-in'
    | '/access-request'
    | '/home'
    | '/my-updates'
    | '/admin/week-updates'
    | '/admin/category'
    | '/admin/members'
    | '/admin/projects'
    | '/admin/'
    | '/sign-in/'
    | '/admin/week-updates/$projectId'
    | '/admin/week-updates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SignInRouteRoute: typeof SignInRouteRouteWithChildren
  AccessRequestRoute: typeof AccessRequestRoute
  HomeRoute: typeof HomeRoute
  MyUpdatesRoute: typeof MyUpdatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-updates': {
      id: '/my-updates'
      path: '/my-updates'
      fullPath: '/my-updates'
      preLoaderRoute: typeof MyUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-request': {
      id: '/access-request'
      path: '/access-request'
      fullPath: '/access-request'
      preLoaderRoute: typeof AccessRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof SignInRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/category': {
      id: '/admin/category'
      path: '/category'
      fullPath: '/admin/category'
      preLoaderRoute: typeof AdminCategoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/week-updates': {
      id: '/admin/week-updates'
      path: '/week-updates'
      fullPath: '/admin/week-updates'
      preLoaderRoute: typeof AdminWeekUpdatesRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/week-updates/': {
      id: '/admin/week-updates/'
      path: '/'
      fullPath: '/admin/week-updates/'
      preLoaderRoute: typeof AdminWeekUpdatesIndexRouteImport
      parentRoute: typeof AdminWeekUpdatesRouteRoute
    }
    '/admin/week-updates/$projectId': {
      id: '/admin/week-updates/$projectId'
      path: '/$projectId'
      fullPath: '/admin/week-updates/$projectId'
      preLoaderRoute: typeof AdminWeekUpdatesProjectIdRouteImport
      parentRoute: typeof AdminWeekUpdatesRouteRoute
    }
  }
}

interface AdminWeekUpdatesRouteRouteChildren {
  AdminWeekUpdatesProjectIdRoute: typeof AdminWeekUpdatesProjectIdRoute
  AdminWeekUpdatesIndexRoute: typeof AdminWeekUpdatesIndexRoute
}

const AdminWeekUpdatesRouteRouteChildren: AdminWeekUpdatesRouteRouteChildren = {
  AdminWeekUpdatesProjectIdRoute: AdminWeekUpdatesProjectIdRoute,
  AdminWeekUpdatesIndexRoute: AdminWeekUpdatesIndexRoute,
}

const AdminWeekUpdatesRouteRouteWithChildren =
  AdminWeekUpdatesRouteRoute._addFileChildren(
    AdminWeekUpdatesRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminWeekUpdatesRouteRoute: typeof AdminWeekUpdatesRouteRouteWithChildren
  AdminCategoryRoute: typeof AdminCategoryRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminWeekUpdatesRouteRoute: AdminWeekUpdatesRouteRouteWithChildren,
  AdminCategoryRoute: AdminCategoryRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SignInRouteRouteChildren {
  SignInIndexRoute: typeof SignInIndexRoute
}

const SignInRouteRouteChildren: SignInRouteRouteChildren = {
  SignInIndexRoute: SignInIndexRoute,
}

const SignInRouteRouteWithChildren = SignInRouteRoute._addFileChildren(
  SignInRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SignInRouteRoute: SignInRouteRouteWithChildren,
  AccessRequestRoute: AccessRequestRoute,
  HomeRoute: HomeRoute,
  MyUpdatesRoute: MyUpdatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
